language: go
before_install:
- openssl aes-256-cbc -K $encrypted_e2786c88889f_key -iv $encrypted_e2786c88889f_iv
  -in .scwrc.enc -out $HOME/.scwrc -d
- chmod 600 $HOME/.scwrc
install:
- go get -u github.com/scaleway/scaleway-cli/cmd/scw
- go install github.com/scaleway/scaleway-cli/cmd/scw

script:
- if [[ $TRAVIS_TAG == "" ]]; 
  then
    $GOPATH/bin/scw create --commercial-type=arm64-4gb -v 50GB --name="travis-$TRAVIS_JOB_ID" image-build &&\
    $GOPATH/bin/scw start -w travis-$TRAVIS_JOB_ID &&\
    $GOPATH/bin/scw stop travis-$TRAVIS_JOB_ID &&\
    $GOPATH/bin/scw wait server &&\
    $GOPATH/bin/scw commit -v 1 travis-$TRAVIS_JOB_ID &&\
    VOLUME1 = $($GOPATH/bin/scw inspect -f '{{with index .Volumes "0"}}{{.Identifier}}{{end}}' travis-$TRAVIS_JOB_ID) &&\
    VOLUME2 = $($GOPATH/bin/scw inspect -f '{{with index .Volumes "0"}}{{.Identifier}}{{end}}' travis-$TRAVIS_JOB_ID) &&\
    $GOPATH/bin/scw rm travis-$TRAVIS_JOB_ID  &&\
    $GOPATH/bin/scw rmi $VOLUME1 &&\
    $GOPATH/bin/scw rmi $VOLUME2;
  fi


